# Generated by Django 5.0.7 on 2024-08-02 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id_analisis', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('titulo_descriptivo', models.CharField(max_length=100)),
                ('periodo', models.CharField(choices=[('DIA', 'Dia'), ('MES', 'Mes'), ('AÑO', 'Año')], default=None, max_length=3)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_paso', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('file', models.FileField(blank=True, null=True, upload_to='datos_xls/')),
                ('comentario', models.TextField(default='Escribe aqui tu comentario', max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos Analisis',
                'verbose_name_plural': 'Analisis',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoCEP',
            fields=[
                ('id_cep', models.AutoField(primary_key=True, serialize=False)),
                ('resultados', models.JSONField(default=dict)),
                ('pid', models.JSONField(default=dict)),
                ('analisis', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analisis_cep', to='aepro.analisis')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoFDA',
            fields=[
                ('id_fda', models.AutoField(primary_key=True, serialize=False)),
                ('resultados', models.JSONField(default=dict)),
                ('pid', models.JSONField(default=dict)),
                ('analisis', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analisis_fda', to='aepro.analisis')),
            ],
        ),
    ]
